// ============================================================
// 信源目录
// ============================================================
window.SOURCES = {
  ccgp:       { name: "中国政府采购网",         url: "https://www.ccgp.gov.cn/cggg/zygg/",          kind: "crawler", note: "财政部指定政府采购信息发布媒体" },
  ctbpsp:     { name: "中国招标投标公共服务平台", url: "https://ctbpsp.com/",                          kind: "crawler", note: "国家级电子招投标公共服务平台,跨平台聚合搜索" },
  qianlima:   { name: "千里马招标网",           url: "https://www.qianlima.com/zb/?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA",                kind: "crawler", note: "综合招标信息聚合,按行业/地区分类" },
  robot_cn:   { name: "中国机器人网",           url: "https://www.robot-china.com/news/list.php?catid=10", kind: "media", note: "机器人行业资讯与企业供需对接" },
  caigou:     { name: "政府采购信息报",         url: "https://www.caigou2003.com/",                 kind: "crawler", note: "政府采购领域行业媒体" },
  gzggzy:     { name: "广州公共资源交易中心",    url: "https://www.gzggzy.cn/",                       kind: "crawler", note: "广州市公共资源交易" },
  suzhou:     { name: "苏州市公共资源交易平台",  url: "https://ggzy.suzhou.gov.cn/",                  kind: "crawler", note: "苏州市本级政府采购" },
  hunan_ggzy: { name: "湖南公共资源交易中心",    url: "https://ggzy.hunan.gov.cn/",                   kind: "crawler", note: "湖南省公共资源交易" },
  cainiao:    { name: "菜鸟合作伙伴",           url: "https://www.cainiao.com/",                    kind: "manual",  note: "菜鸟对外合作页面" },
  jdl:        { name: "京东物流",               url: "https://www.jdl.com/",                        kind: "manual",  note: "京东物流招采对接页" },
  meituan:    { name: "美团生态",               url: "https://about.meituan.com/",                  kind: "manual",  note: "美团生态合作与商家招募" },
  bytedance:  { name: "字节跳动",               url: "https://www.bytedance.com/zh/",               kind: "manual",  note: "字节跳动公开页面" },
  foxconn:    { name: "富士康",                 url: "https://www.foxconn.com.cn/",                 kind: "manual",  note: "富士康集团官网" },

  // ===== 第二次新增信源(2026-07-18 补充第二批)=====
  // 综合招标聚合 - 已抓
  chinabidding: { name: "中招国际",              url: "https://www.chinabidding.com/bidDetail/261828686.html",                kind: "crawler", note: "中国国际招标采购网,有 bidDetail/infoDetail 详情页" },
  // 行业媒体 - 已抓
  robot_industry:{ name: "中国机器人网",          url: "https://www.robot-china.com/news/",            kind: "media",    note: "机器人行业新闻/产业动态/news/YYYYMM/DD/ID.html" },
  // 公共采购 - 已抓
  cgpnews:      { name: "中国公共采购网",        url: "http://www.cgpnews.cn/",                       kind: "crawler", note: "政府采购信息发布,articles/ID.html" },

  // ===== 新增信源(2026-07-18 补充)=====
  // 地方公共资源
  js_ggzy:       { name: "江苏省公共资源交易",    url: "http://www.jszwfw.gov.cn/",                      kind: "crawler", note: "江苏省综合政府采购与工程交易" },
  tj_ggzy:       { name: "天津公共资源交易中心",  url: "https://www.tjggzy.cn/",                        kind: "crawler", note: "天津市级政府采购" },
  cq_ggzy:       { name: "重庆公共资源交易中心",  url: "https://www.cqggzy.com/",                       kind: "crawler", note: "重庆市政府采购与产权交易" },
  sc_ggzy:       { name: "四川公共资源",          url: "https://www.sczwfw.gov.cn/",                    kind: "crawler", note: "四川省政务服务公共资源" },
  js_zfcg:       { name: "江苏政府采购网",        url: "http://www.ccgp-jiangsu.gov.cn/",               kind: "crawler", note: "江苏省政府采购专网" },
  zjggzy:        { name: "浙江省公共资源交易中心",  url: "https://www.ggzy.zj.gov.cn/",                   kind: "crawler", note: "浙江省级公共资源" },

  // 综合招标聚合
  ebnew:         { name: "必联网",                url: "https://www.ebnew.com/?keyword=%E6%9C%BA%E5%99%A8%E4%BA%BA",                        kind: "crawler", note: "中国 B2B 招标采购信息聚合" },
  trade365:      { name: "中招联合",              url: "https://www.365trade.com.cn/?keyword=%E6%9C%BA%E5%99%A8%E4%BA%BA",                  kind: "crawler", note: "央企/政府/医院 招标信息聚合" },
  bidradar:      { name: "招标雷达",              url: "https://www.bidradar.com/?keyword=%E6%9C%BA%E5%99%A8%E4%BA%BA",                     kind: "crawler", note: "招标项目智能雷达" },
  bidizhaobiao:  { name: "比地招标",              url: "https://www.bidizhaobiao.com/",                 kind: "crawler", note: "工程招标项目信息聚合" },
  chinapurchasing: { name: "中国采购网",          url: "https://www.chinapurchasing.com/",              kind: "crawler", note: "全国招投标信息聚合" },

  // 央企/能源
  sasac:         { name: "国务院国资委",          url: "http://www.sasac.gov.cn/",                      kind: "crawler", note: "央企招投标信息汇聚" },
  sgcc:          { name: "国家电网电子商务平台",  url: "https://ecp.sgcc.com.cn/",                      kind: "crawler", note: "国网采购公告与招标信息" },
  csg:           { name: "南方电网采购",          url: "https://www.bidding.csg.cn/",                   kind: "crawler", note: "南网招标采购" },
  cnpc:          { name: "中石油招标",            url: "http://www.cnpcbidding.com/",                   kind: "crawler", note: "中石油招投标网" },
  sinopec:       { name: "中石化招标",            url: "https://ebidding.sinopec.com/",                 kind: "crawler", note: "中石化电子招投标" },
  mobile10086:   { name: "中国移动采购",          url: "https://b2b.10086.cn/",                         kind: "crawler", note: "中移动 B2B 采购平台" },
  ceec:          { name: "中能建招标",            url: "http://www.ceec.net.cn/",                       kind: "crawler", note: "中能建采购" },
  powerchina:    { name: "中电建采购",            url: "https://www.powerchina.cn/",                    kind: "crawler", note: "中电建采购" },
  cnbm:          { name: "中建材采购",            url: "https://www.cnbm.com.cn/",                      kind: "crawler", note: "中建材集团采购" },
  ccic:          { name: "中检集团采购",          url: "https://www.ccic.com/",                         kind: "crawler", note: "中检集团招采" },
  cas:           { name: "中科院采购",            url: "https://www.cas.cn/",                           kind: "crawler", note: "中科院仪器设备与工程采购" },
  avicbid:       { name: "中航招标",              url: "http://www.avicbid.com/",                       kind: "crawler", note: "中航工业电子采购平台" },

  // 行业媒体
  ofweek_robot:  { name: "OFweek 机器人",         url: "https://robot.ofweek.com/",                     kind: "media",   note: "机器人行业媒体" },

  // 政采云
  zcygov:        { name: "政采云",                url: "https://www.zcygov.cn/",                        kind: "crawler", note: "浙江省政府采购云平台" },
  gjzwfw:        { name: "国家政务服务平台",      url: "https://www.gjzwfw.gov.cn/",                    kind: "crawler", note: "全国一体化政务服务总入口" }
};

// ============================================================
// 25 条 lead — 全部从中国政府采购网 (CCGP) 实际抓取
// 抓取时间: 2026-07-18
// 抓取方式: search.ccgp.gov.cn 关键词搜索 (机器人/无人机/智能体/机械臂/巡检)
// ============================================================ — 全部从中国政府采购网 (CCGP) 实际抓取
// 抓取时间: 2026-07-18
// 抓取方式: search.ccgp.gov.cn 关键词搜索 (机器人/无人机/智能体/机械臂/巡检)
// ============================================================
window.LEADS = [
  {
    "id": 1,
    "lead_type": "procurement",
    "title": "成都工业职业技术学院智改数转智能机器人育训平台项目(四次)招标公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "成都工业职业技术学院智改数转智能机器人育训平台项目(四次)招标公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26965351.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "成都工业职业技术学院智改数转智能机器人育训平台项目(四次)招标公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26965351.htm",
    "is_real": true
  },
  {
    "id": 2,
    "lead_type": "procurement",
    "title": "黄石市中心医院黄石市中心医院腹腔内窥镜手术系统（手术机器人）配套附件一批采购项目采购实行单一来源采购方式的公示",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "黄石市中心医院黄石市中心医院腹腔内窥镜手术系统（手术机器人）配套附件一批采购项目采购实行单一来源采购方式的公示",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/dylygg/202607/t20260720_26965204.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "黄石市中心医院黄石市中心医院腹腔内窥镜手术系统（手术机器人）配套附件一批采购项目采购实行单一来源采购方式的公示\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/dylygg/202607/t20260720_26965204.htm",
    "is_real": true
  },
  {
    "id": 3,
    "lead_type": "procurement",
    "title": "青岛市市立医院青岛市市立医院东院达芬奇机器人设备维保服务项目更正公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "青岛市市立医院青岛市市立医院东院达芬奇机器人设备维保服务项目更正公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/gzgg/202607/t20260720_26965019.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "青岛市市立医院青岛市市立医院东院达芬奇机器人设备维保服务项目更正公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/gzgg/202607/t20260720_26965019.htm",
    "is_real": true
  },
  {
    "id": 4,
    "lead_type": "procurement",
    "title": "广州市机电技师学院专业实训设备及教学设施购置项目（2026年）子项目3：工业机器人实训设备购置项目招标公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "广州市机电技师学院专业实训设备及教学设施购置项目（2026年）子项目3：工业机器人实训设备购置项目招标公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["广州"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26964831.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "广州市机电技师学院专业实训设备及教学设施购置项目（2026年）子项目3：工业机器人实训设备购置项目招标公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26964831.htm",
    "is_real": true
  },
  {
    "id": 5,
    "lead_type": "procurement",
    "title": "中南大学湘雅二医院达芬奇手术机器人维保服务项目中标（成交）结果公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "中南大学湘雅二医院达芬奇手术机器人维保服务项目中标（成交）结果公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/zygg/cjgg/202607/t20260720_26964714.htm"}],
    "status": "won",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "中南大学湘雅二医院达芬奇手术机器人维保服务项目中标（成交）结果公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/zygg/cjgg/202607/t20260720_26964714.htm",
    "is_real": true
  },
  {
    "id": 6,
    "lead_type": "procurement",
    "title": "工业机器人应用编程实训室升级（第二次）更正公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "工业机器人应用编程实训室升级（第二次）更正公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/gzgg/202607/t20260720_26964362.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "工业机器人应用编程实训室升级（第二次）更正公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/gzgg/202607/t20260720_26964362.htm",
    "is_real": true
  },
  {
    "id": 7,
    "lead_type": "procurement",
    "title": "华中农业大学农业智能装备创新支撑中心项目第三十批（机器人快速标定系统等设备）中标公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "华中农业大学农业智能装备创新支撑中心项目第三十批（机器人快速标定系统等设备）中标公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/zygg/zbgg/202607/t20260720_26963800.htm"}],
    "status": "won",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "华中农业大学农业智能装备创新支撑中心项目第三十批（机器人快速标定系统等设备）中标公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/zygg/zbgg/202607/t20260720_26963800.htm",
    "is_real": true
  },
  {
    "id": 8,
    "lead_type": "procurement",
    "title": "华中农业大学农业智能装备创新支撑中心项目第三十一批（机器人高精度高速动作追踪实验平台系统等设备）中标公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "华中农业大学农业智能装备创新支撑中心项目第三十一批（机器人高精度高速动作追踪实验平台系统等设备）中标公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/zygg/zbgg/202607/t20260720_26963799.htm"}],
    "status": "won",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "华中农业大学农业智能装备创新支撑中心项目第三十一批（机器人高精度高速动作追踪实验平台系统等设备）中标公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/zygg/zbgg/202607/t20260720_26963799.htm",
    "is_real": true
  },
  {
    "id": 9,
    "lead_type": "procurement",
    "title": "延寿县农业技术推广中心防治药剂叶面肥无人机作业服务中标（成交）结果公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "延寿县农业技术推广中心防治药剂叶面肥无人机作业服务中标（成交）结果公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/cjgg/202607/t20260720_26965411.htm"}],
    "status": "won",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "延寿县农业技术推广中心防治药剂叶面肥无人机作业服务中标（成交）结果公告\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/cjgg/202607/t20260720_26965411.htm",
    "is_real": true
  },
  {
    "id": 10,
    "lead_type": "procurement",
    "title": "辽宁开放大学（辽宁装备制造职业技术学院）无人机虚拟仿真实训室建设招标公告(JH26-210000-24789(LNZC2026-0206))",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "辽宁开放大学（辽宁装备制造职业技术学院）无人机虚拟仿真实训室建设招标公告(JH26-210000-24789(LNZC2026-0206))",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["辽宁"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国政府采购网",
    "sources": [{"source_name": "中国政府采购网", "url": "http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26964814.htm"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "辽宁开放大学（辽宁装备制造职业技术学院）无人机虚拟仿真实训室建设招标公告(JH26-210000-24789(LNZC2026-0206))\n来源:中国政府采购网 http://www.ccgp.gov.cn/cggg/dfgg/gkzb/202607/t20260720_26964814.htm",
    "is_real": true
  },
  {
    "id": 11,
    "lead_type": "procurement",
    "title": "国家发展改革委等部门关于加快招标投标领域人工智能推广应用的实施意见",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "国家发展改革委等部门关于加快招标投标领域人工智能推广应用的实施意见",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中招国际",
    "sources": [{"source_name": "中招国际", "url": "https://www.chinabidding.com/infoDetail/262389554-News.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "国家发展改革委等部门关于加快招标投标领域人工智能推广应用的实施意见\n来源:中招国际 https://www.chinabidding.com/infoDetail/262389554-News.html",
    "is_real": true
  },
  {
    "id": 12,
    "lead_type": "procurement",
    "title": "2025-2026年度溪洛渡水电站机械设备检修项目公告",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "2025-2026年度溪洛渡水电站机械设备检修项目公告",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中招国际",
    "sources": [{"source_name": "中招国际", "url": "https://www.chinabidding.com/bidDetail/261828686.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "2025-2026年度溪洛渡水电站机械设备检修项目公告\n来源:中招国际 https://www.chinabidding.com/bidDetail/261828686.html",
    "is_real": true
  },
  {
    "id": 15,
    "lead_type": "procurement",
    "title": "机器人_资讯搜索_中国机器人网",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人_资讯搜索_中国机器人网",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人_资讯搜索_中国机器人网\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 16,
    "lead_type": "procurement",
    "title": "工业机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "工业机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%B7%A5%E4%B8%9A%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "工业机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%B7%A5%E4%B8%9A%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 17,
    "lead_type": "procurement",
    "title": "机器人产业联盟",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人产业联盟",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BA%A7%E4%B8%9A%E8%81%94%E7%9B%9F"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人产业联盟\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BA%A7%E4%B8%9A%E8%81%94%E7%9B%9F",
    "is_real": true
  },
  {
    "id": 18,
    "lead_type": "procurement",
    "title": "机器人展览",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人展览",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%B1%95%E8%A7%88"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人展览\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%B1%95%E8%A7%88",
    "is_real": true
  },
  {
    "id": 19,
    "lead_type": "procurement",
    "title": "人形机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "人形机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://jqrz.cn/"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "人形机器人\n来源:中国机器人网 https://jqrz.cn/",
    "is_real": true
  },
  {
    "id": 20,
    "lead_type": "procurement",
    "title": "卫浴“单项冠军”锚定机器人配套 艾芬达探索第二增长极",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "卫浴“单项冠军”锚定机器人配套 艾芬达探索第二增长极",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/20/96139.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "卫浴“单项冠军”锚定机器人配套 艾芬达探索第二增长极\n来源:中国机器人网 https://www.robot-china.com/news/202607/20/96139.html",
    "is_real": true
  },
  {
    "id": 21,
    "lead_type": "procurement",
    "title": "服务型完全仿生机器人迎来落地窗口期，卓益得 Moya 完成场景、量产双重验证",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "服务型完全仿生机器人迎来落地窗口期，卓益得 Moya 完成场景、量产双重验证",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/20/96138.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "服务型完全仿生机器人迎来落地窗口期，卓益得 Moya 完成场景、量产双重验证\n来源:中国机器人网 https://www.robot-china.com/news/202607/20/96138.html",
    "is_real": true
  },
  {
    "id": 22,
    "lead_type": "procurement",
    "title": "PNDbotics亮相WAIC 2026：全尺寸人形机器人首秀“走楼梯”，双模型同台验证具身智能新生态",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "PNDbotics亮相WAIC 2026：全尺寸人形机器人首秀“走楼梯”，双模型同台验证具身智能新生态",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-10",
    "published_at": "2026-07-20",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/20/96136.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "PNDbotics亮相WAIC 2026：全尺寸人形机器人首秀“走楼梯”，双模型同台验证具身智能新生态\n来源:中国机器人网 https://www.robot-china.com/news/202607/20/96136.html",
    "is_real": true
  },
  {
    "id": 23,
    "lead_type": "procurement",
    "title": "直击越疆Physical AI：会思考、善操作机器人的精准作业闭环",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "直击越疆Physical AI：会思考、善操作机器人的精准作业闭环",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96131.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "直击越疆Physical AI：会思考、善操作机器人的精准作业闭环\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96131.html",
    "is_real": true
  },
  {
    "id": 24,
    "lead_type": "procurement",
    "title": "链上发力，浙江云芯机器人以核心零部件赋能机器人产业集群",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "链上发力，浙江云芯机器人以核心零部件赋能机器人产业集群",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["浙江"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96128.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "链上发力，浙江云芯机器人以核心零部件赋能机器人产业集群\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96128.html",
    "is_real": true
  },
  {
    "id": 25,
    "lead_type": "procurement",
    "title": "搭载中国4D世界模型的具身机器人进入越南工厂，影身智能“卖本体+卖Token”模式开辟中国科技成果出海新范式",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "搭载中国4D世界模型的具身机器人进入越南工厂，影身智能“卖本体+卖Token”模式开辟中国科技成果出海新范式",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96125.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "搭载中国4D世界模型的具身机器人进入越南工厂，影身智能“卖本体+卖Token”模式开辟中国科技成果出海新范式\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96125.html",
    "is_real": true
  },
  {
    "id": 26,
    "lead_type": "procurement",
    "title": "工业和信息化部人形机器人与具身智能标准化技术委员会2026年度全体会议暨“标准周”活动在浙江绍兴召开",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "工业和信息化部人形机器人与具身智能标准化技术委员会2026年度全体会议暨“标准周”活动在浙江绍兴召开",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["浙江"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96124.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "工业和信息化部人形机器人与具身智能标准化技术委员会2026年度全体会议暨“标准周”活动在浙江绍兴召开\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96124.html",
    "is_real": true
  },
  {
    "id": 27,
    "lead_type": "procurement",
    "title": "云迹科技WAIC首发“世界价值模型”，服务机器人行业迈入“空间智能”下半场",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "云迹科技WAIC首发“世界价值模型”，服务机器人行业迈入“空间智能”下半场",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96120.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "云迹科技WAIC首发“世界价值模型”，服务机器人行业迈入“空间智能”下半场\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96120.html",
    "is_real": true
  },
  {
    "id": 28,
    "lead_type": "procurement",
    "title": "赛迪传媒与励展博览集团关于2026智能机器人博览会（ROBOTECH）达成战略合作，展会聚焦应用场景全面升级！",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "赛迪传媒与励展博览集团关于2026智能机器人博览会（ROBOTECH）达成战略合作，展会聚焦应用场景全面升级！",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96119.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "赛迪传媒与励展博览集团关于2026智能机器人博览会（ROBOTECH）达成战略合作，展会聚焦应用场景全面升级！\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96119.html",
    "is_real": true
  },
  {
    "id": 29,
    "lead_type": "procurement",
    "title": "思灵机器人 Agile Robots亮相WAIC 2026：具身智能独角兽展示物理AI全栈实力",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "思灵机器人 Agile Robots亮相WAIC 2026：具身智能独角兽展示物理AI全栈实力",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96118.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "思灵机器人 Agile Robots亮相WAIC 2026：具身智能独角兽展示物理AI全栈实力\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96118.html",
    "is_real": true
  },
  {
    "id": 30,
    "lead_type": "procurement",
    "title": "AIROBO重磅发布机器人行业首个第三方开放接口标准",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "AIROBO重磅发布机器人行业首个第三方开放接口标准",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96110.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "AIROBO重磅发布机器人行业首个第三方开放接口标准\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96110.html",
    "is_real": true
  },
  {
    "id": 31,
    "lead_type": "procurement",
    "title": "不靠人手靠技术！俏妃AI推拿机器人重构养生服务逻辑",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "不靠人手靠技术！俏妃AI推拿机器人重构养生服务逻辑",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96109.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "不靠人手靠技术！俏妃AI推拿机器人重构养生服务逻辑\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96109.html",
    "is_real": true
  },
  {
    "id": 32,
    "lead_type": "procurement",
    "title": "与哈金森达成战略合作，乐聚机器人何以获得全球工业巨头持续青睐？",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "与哈金森达成战略合作，乐聚机器人何以获得全球工业巨头持续青睐？",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96106.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "与哈金森达成战略合作，乐聚机器人何以获得全球工业巨头持续青睐？\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96106.html",
    "is_real": true
  },
  {
    "id": 33,
    "lead_type": "procurement",
    "title": "机器人龙头越疆科技创业板IPO即将上会，用时仅86天！",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人龙头越疆科技创业板IPO即将上会，用时仅86天！",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96104.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人龙头越疆科技创业板IPO即将上会，用时仅86天！\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96104.html",
    "is_real": true
  },
  {
    "id": 34,
    "lead_type": "procurement",
    "title": "科沃斯首款开源机器人线下空间揭牌，具身智能生态布局再进一步",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "科沃斯首款开源机器人线下空间揭牌，具身智能生态布局再进一步",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96103.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "科沃斯首款开源机器人线下空间揭牌，具身智能生态布局再进一步\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96103.html",
    "is_real": true
  },
  {
    "id": 35,
    "lead_type": "procurement",
    "title": "拉条子、穿串、烤串、切菜，睿尔曼机器人化身“新疆大厨”完成多项实景挑战",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "拉条子、穿串、烤串、切菜，睿尔曼机器人化身“新疆大厨”完成多项实景挑战",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["新疆"],
    "deadline": "2026-08-06",
    "published_at": "2026-07-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/16/96100.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "拉条子、穿串、烤串、切菜，睿尔曼机器人化身“新疆大厨”完成多项实景挑战\n来源:中国机器人网 https://www.robot-china.com/news/202607/16/96100.html",
    "is_real": true
  },
  {
    "id": 36,
    "lead_type": "procurement",
    "title": "OTA V3.0正式上线丨Bumi小布米个人机器人全新迭代，开启全民智能陪伴新时代",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "OTA V3.0正式上线丨Bumi小布米个人机器人全新迭代，开启全民智能陪伴新时代",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/15/96099.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "OTA V3.0正式上线丨Bumi小布米个人机器人全新迭代，开启全民智能陪伴新时代\n来源:中国机器人网 https://www.robot-china.com/news/202607/15/96099.html",
    "is_real": true
  },
  {
    "id": 37,
    "lead_type": "procurement",
    "title": "中国国际经济技术合作促进会启动《协作机器人模块化机械臂 通用接口要求》团体标准制定",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "中国国际经济技术合作促进会启动《协作机器人模块化机械臂 通用接口要求》团体标准制定",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["国际"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/15/96097.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "中国国际经济技术合作促进会启动《协作机器人模块化机械臂 通用接口要求》团体标准制定\n来源:中国机器人网 https://www.robot-china.com/news/202607/15/96097.html",
    "is_real": true
  },
  {
    "id": 38,
    "lead_type": "procurement",
    "title": "2027中国人形机器人生态大会将于2027年4月16-18日举行",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "2027中国人形机器人生态大会将于2027年4月16-18日举行",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/15/96095.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "2027中国人形机器人生态大会将于2027年4月16-18日举行\n来源:中国机器人网 https://www.robot-china.com/news/202607/15/96095.html",
    "is_real": true
  },
  {
    "id": 39,
    "lead_type": "procurement",
    "title": "具身机器人进车厂：越疆交付可迭代的新质生产力",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "具身机器人进车厂：越疆交付可迭代的新质生产力",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/15/96094.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "具身机器人进车厂：越疆交付可迭代的新质生产力\n来源:中国机器人网 https://www.robot-china.com/news/202607/15/96094.html",
    "is_real": true
  },
  {
    "id": 40,
    "lead_type": "procurement",
    "title": "独家｜千觉机器人完成亿元融资，加速物理智能触觉感知、数据与模型体系落地",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "独家｜千觉机器人完成亿元融资，加速物理智能触觉感知、数据与模型体系落地",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-04",
    "published_at": "2026-07-14",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/14/96092.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "独家｜千觉机器人完成亿元融资，加速物理智能触觉感知、数据与模型体系落地\n来源:中国机器人网 https://www.robot-china.com/news/202607/14/96092.html",
    "is_real": true
  },
  {
    "id": 41,
    "lead_type": "procurement",
    "title": "人形机器人核心供应链最新横评：传动与结构件赛道选型参考",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "人形机器人核心供应链最新横评：传动与结构件赛道选型参考",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-04",
    "published_at": "2026-07-14",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/14/96089.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "人形机器人核心供应链最新横评：传动与结构件赛道选型参考\n来源:中国机器人网 https://www.robot-china.com/news/202607/14/96089.html",
    "is_real": true
  },
  {
    "id": 42,
    "lead_type": "procurement",
    "title": "共话人机共生 2026机器人企业家尼山峰会于济宁启幕",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "共话人机共生 2026机器人企业家尼山峰会于济宁启幕",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-03",
    "published_at": "2026-07-13",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/13/96085.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "共话人机共生 2026机器人企业家尼山峰会于济宁启幕\n来源:中国机器人网 https://www.robot-china.com/news/202607/13/96085.html",
    "is_real": true
  },
  {
    "id": 43,
    "lead_type": "procurement",
    "title": "全球首个获工业级全域CE认证的具身智能机器人！无界动力K15开启全球批量交付",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "全球首个获工业级全域CE认证的具身智能机器人！无界动力K15开启全球批量交付",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-31",
    "published_at": "2026-07-10",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/10/96081.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "全球首个获工业级全域CE认证的具身智能机器人！无界动力K15开启全球批量交付\n来源:中国机器人网 https://www.robot-china.com/news/202607/10/96081.html",
    "is_real": true
  },
  {
    "id": 44,
    "lead_type": "procurement",
    "title": "汉普智造一站式PCBA服务解析：如何赋能AI算力、机器人与智能硬件从设计到量产？",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "汉普智造一站式PCBA服务解析：如何赋能AI算力、机器人与智能硬件从设计到量产？",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-31",
    "published_at": "2026-07-10",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/10/96080.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "汉普智造一站式PCBA服务解析：如何赋能AI算力、机器人与智能硬件从设计到量产？\n来源:中国机器人网 https://www.robot-china.com/news/202607/10/96080.html",
    "is_real": true
  },
  {
    "id": 45,
    "lead_type": "procurement",
    "title": "村田中国亮相2026慕尼黑上海电子展 四大领域及人形机器人创新方案智启无界新生",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "村田中国亮相2026慕尼黑上海电子展 四大领域及人形机器人创新方案智启无界新生",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["上海"],
    "deadline": "2026-07-30",
    "published_at": "2026-07-09",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/09/96069.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "村田中国亮相2026慕尼黑上海电子展 四大领域及人形机器人创新方案智启无界新生\n来源:中国机器人网 https://www.robot-china.com/news/202607/09/96069.html",
    "is_real": true
  },
  {
    "id": 46,
    "lead_type": "procurement",
    "title": "6位博士跨界融合，俏妃AI推拿机器人筑起创新底座",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "6位博士跨界融合，俏妃AI推拿机器人筑起创新底座",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-30",
    "published_at": "2026-07-09",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/09/96063.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "6位博士跨界融合，俏妃AI推拿机器人筑起创新底座\n来源:中国机器人网 https://www.robot-china.com/news/202607/09/96063.html",
    "is_real": true
  },
  {
    "id": 47,
    "lead_type": "procurement",
    "title": "EBC 2026具身智能与人形机器人智脑科技大会9月18日在上海盛大开幕！",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "EBC 2026具身智能与人形机器人智脑科技大会9月18日在上海盛大开幕！",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["上海"],
    "deadline": "2026-07-29",
    "published_at": "2026-07-08",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/08/96061.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "EBC 2026具身智能与人形机器人智脑科技大会9月18日在上海盛大开幕！\n来源:中国机器人网 https://www.robot-china.com/news/202607/08/96061.html",
    "is_real": true
  },
  {
    "id": 48,
    "lead_type": "procurement",
    "title": "探秘佛山全球最大服务机器人产业园：一台扫地机从零件到整机的智造之旅",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "探秘佛山全球最大服务机器人产业园：一台扫地机从零件到整机的智造之旅",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-29",
    "published_at": "2026-07-08",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/08/96058.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "探秘佛山全球最大服务机器人产业园：一台扫地机从零件到整机的智造之旅\n来源:中国机器人网 https://www.robot-china.com/news/202607/08/96058.html",
    "is_real": true
  },
  {
    "id": 49,
    "lead_type": "procurement",
    "title": "海宝等离子切割与气刨+协作机器人解决方案亮相2026埃森展",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "海宝等离子切割与气刨+协作机器人解决方案亮相2026埃森展",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-29",
    "published_at": "2026-07-08",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/08/96057.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "海宝等离子切割与气刨+协作机器人解决方案亮相2026埃森展\n来源:中国机器人网 https://www.robot-china.com/news/202607/08/96057.html",
    "is_real": true
  },
  {
    "id": 50,
    "lead_type": "procurement",
    "title": "码垛机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "码垛机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E7%A0%81%E5%9E%9B%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "码垛机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E7%A0%81%E5%9E%9B%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 51,
    "lead_type": "procurement",
    "title": "机器人技术",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人技术",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8A%80%E6%9C%AF"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人技术\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8A%80%E6%9C%AF",
    "is_real": true
  },
  {
    "id": 52,
    "lead_type": "procurement",
    "title": "ABB机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "ABB机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=ABB%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "ABB机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=ABB%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 53,
    "lead_type": "procurement",
    "title": "发那科机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "发那科机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%8F%91%E9%82%A3%E7%A7%91%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "发那科机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%8F%91%E9%82%A3%E7%A7%91%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 54,
    "lead_type": "procurement",
    "title": "服务机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "服务机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%8D%E5%8A%A1%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "服务机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%8D%E5%8A%A1%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 55,
    "lead_type": "procurement",
    "title": "人形机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "人形机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E4%BA%BA%E5%BD%A2%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "人形机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E4%BA%BA%E5%BD%A2%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 56,
    "lead_type": "procurement",
    "title": "机器人控制器",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人控制器",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8E%A7%E5%88%B6%E5%99%A8"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人控制器\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8E%A7%E5%88%B6%E5%99%A8",
    "is_real": true
  },
  {
    "id": 57,
    "lead_type": "procurement",
    "title": "智能机器人与未来科技展",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能机器人与未来科技展",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "http://www.irfte.com/"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能机器人与未来科技展\n来源:中国机器人网 http://www.irfte.com/",
    "is_real": true
  },
  {
    "id": 58,
    "lead_type": "procurement",
    "title": "人形机器人生态大会",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "人形机器人生态大会",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "http://chrec.cn/"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "人形机器人生态大会\n来源:中国机器人网 http://chrec.cn/",
    "is_real": true
  },
  {
    "id": 59,
    "lead_type": "procurement",
    "title": "资讯搜索_中国机器人网",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "资讯搜索_中国机器人网",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "资讯搜索_中国机器人网\n来源:中国机器人网 https://www.robot-china.com/news/search.php",
    "is_real": true
  },
  {
    "id": 67,
    "lead_type": "procurement",
    "title": "智能_资讯搜索_中国机器人网",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能_资讯搜索_中国机器人网",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能_资讯搜索_中国机器人网\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD",
    "is_real": true
  },
  {
    "id": 73,
    "lead_type": "procurement",
    "title": "盛会启幕 | WAIC2026世界人工智能大会，数聚链具身智能“大小脑”协同技术重磅亮相！",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "盛会启幕 | WAIC2026世界人工智能大会，数聚链具身智能“大小脑”协同技术重磅亮相！",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96129.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "盛会启幕 | WAIC2026世界人工智能大会，数聚链具身智能“大小脑”协同技术重磅亮相！\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96129.html",
    "is_real": true
  },
  {
    "id": 79,
    "lead_type": "procurement",
    "title": "2027亚洲国际人工智能产业博览会（世亚智博会）全维度介绍",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "2027亚洲国际人工智能产业博览会（世亚智博会）全维度介绍",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["国际"],
    "deadline": "2026-08-07",
    "published_at": "2026-07-17",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/17/96117.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "2027亚洲国际人工智能产业博览会（世亚智博会）全维度介绍\n来源:中国机器人网 https://www.robot-china.com/news/202607/17/96117.html",
    "is_real": true
  },
  {
    "id": 87,
    "lead_type": "procurement",
    "title": "智能机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 88,
    "lead_type": "procurement",
    "title": "智能服务机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能服务机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%8D%E5%8A%A1%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能服务机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%8D%E5%8A%A1%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 89,
    "lead_type": "procurement",
    "title": "智能机器人产业",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能机器人产业",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BA%A7%E4%B8%9A"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能机器人产业\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BA%A7%E4%B8%9A",
    "is_real": true
  },
  {
    "id": 101,
    "lead_type": "procurement",
    "title": "巡检_资讯搜索_中国机器人网",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "巡检_资讯搜索_中国机器人网",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%B7%A1%E6%A3%80"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "巡检_资讯搜索_中国机器人网\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%B7%A1%E6%A3%80",
    "is_real": true
  },
  {
    "id": 106,
    "lead_type": "procurement",
    "title": "风电场站巡检从\"人跑\"到\"智巡\"：科义机器人的全场景方案拆解",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "风电场站巡检从\"人跑\"到\"智巡\"：科义机器人的全场景方案拆解",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-07-24",
    "published_at": "2026-07-03",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202607/03/96024.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "风电场站巡检从\"人跑\"到\"智巡\"：科义机器人的全场景方案拆解\n来源:中国机器人网 https://www.robot-china.com/news/202607/03/96024.html",
    "is_real": true
  },
  {
    "id": 107,
    "lead_type": "procurement",
    "title": "具身智能为文旅注入新活力,智瀚星途机器人五一假期赋能无锡映月里提供导览巡检服务",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "具身智能为文旅注入新活力,智瀚星途机器人五一假期赋能无锡映月里提供导览巡检服务",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-05-27",
    "published_at": "2026-05-06",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202605/06/95553.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "具身智能为文旅注入新活力,智瀚星途机器人五一假期赋能无锡映月里提供导览巡检服务\n来源:中国机器人网 https://www.robot-china.com/news/202605/06/95553.html",
    "is_real": true
  },
  {
    "id": 108,
    "lead_type": "procurement",
    "title": "科义机器人：让工业巡检从\"人海战术\"转向\"智能时代\"",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "科义机器人：让工业巡检从\"人海战术\"转向\"智能时代\"",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-03-30",
    "published_at": "2026-03-09",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202603/09/95145.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "科义机器人：让工业巡检从\"人海战术\"转向\"智能时代\"\n来源:中国机器人网 https://www.robot-china.com/news/202603/09/95145.html",
    "is_real": true
  },
  {
    "id": 109,
    "lead_type": "procurement",
    "title": "从\"不得不做\"到\"放心让它做\"——工业巡检的人机协作革命",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "从\"不得不做\"到\"放心让它做\"——工业巡检的人机协作革命",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-02-18",
    "published_at": "2026-01-28",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202601/28/94975.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "从\"不得不做\"到\"放心让它做\"——工业巡检的人机协作革命\n来源:中国机器人网 https://www.robot-china.com/news/202601/28/94975.html",
    "is_real": true
  },
  {
    "id": 110,
    "lead_type": "procurement",
    "title": "KAOE科义-药厂智能巡检通用化技术解决方案",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "KAOE科义-药厂智能巡检通用化技术解决方案",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-11-25",
    "published_at": "2025-11-04",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202511/04/94367.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "KAOE科义-药厂智能巡检通用化技术解决方案\n来源:中国机器人网 https://www.robot-china.com/news/202511/04/94367.html",
    "is_real": true
  },
  {
    "id": 111,
    "lead_type": "procurement",
    "title": "机器狗巡检、人形机器人分拣 “未来工位”展示“人工智能+制造”新实践",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器狗巡检、人形机器人分拣 “未来工位”展示“人工智能+制造”新实践",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-11-04",
    "published_at": "2025-10-14",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202510/14/94224.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器狗巡检、人形机器人分拣 “未来工位”展示“人工智能+制造”新实践\n来源:中国机器人网 https://www.robot-china.com/news/202510/14/94224.html",
    "is_real": true
  },
  {
    "id": 112,
    "lead_type": "procurement",
    "title": "搭建跨行业无人机巡检系统，贝锐花生壳如何实现异地视频画面实时回传？",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "搭建跨行业无人机巡检系统，贝锐花生壳如何实现异地视频画面实时回传？",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-10-02",
    "published_at": "2025-09-11",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202509/11/93996.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "搭建跨行业无人机巡检系统，贝锐花生壳如何实现异地视频画面实时回传？\n来源:中国机器人网 https://www.robot-china.com/news/202509/11/93996.html",
    "is_real": true
  },
  {
    "id": 113,
    "lead_type": "procurement",
    "title": "小笨智能机器人登上《新闻联播》，揭秘上合峰会天津边检的智能“巡检员”",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "小笨智能机器人登上《新闻联播》，揭秘上合峰会天津边检的智能“巡检员”",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["天津"],
    "deadline": "2025-09-24",
    "published_at": "2025-09-03",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202509/03/93914.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "小笨智能机器人登上《新闻联播》，揭秘上合峰会天津边检的智能“巡检员”\n来源:中国机器人网 https://www.robot-china.com/news/202509/03/93914.html",
    "is_real": true
  },
  {
    "id": 114,
    "lead_type": "procurement",
    "title": "新闻联播关注！列车巡检 效率翻倍，这位节卡机器人同志竟能在1小时点检万余项点？",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "新闻联播关注！列车巡检 效率翻倍，这位节卡机器人同志竟能在1小时点检万余项点？",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-09-18",
    "published_at": "2025-08-28",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202508/28/93867.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "新闻联播关注！列车巡检 效率翻倍，这位节卡机器人同志竟能在1小时点检万余项点？\n来源:中国机器人网 https://www.robot-china.com/news/202508/28/93867.html",
    "is_real": true
  },
  {
    "id": 115,
    "lead_type": "procurement",
    "title": "四足式机器人智能巡检 守护地下“动脉”",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "四足式机器人智能巡检 守护地下“动脉”",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-09-17",
    "published_at": "2025-08-27",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202508/27/93849.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "四足式机器人智能巡检 守护地下“动脉”\n来源:中国机器人网 https://www.robot-china.com/news/202508/27/93849.html",
    "is_real": true
  },
  {
    "id": 116,
    "lead_type": "procurement",
    "title": "巡检机器狗怎么选？4大关键指标教你避坑",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "巡检机器狗怎么选？4大关键指标教你避坑",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-09-11",
    "published_at": "2025-08-21",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202508/21/93811.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "巡检机器狗怎么选？4大关键指标教你避坑\n来源:中国机器人网 https://www.robot-china.com/news/202508/21/93811.html",
    "is_real": true
  },
  {
    "id": 117,
    "lead_type": "procurement",
    "title": "循轨识弊 速破困局—科义轨道式巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "循轨识弊 速破困局—科义轨道式巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-09-02",
    "published_at": "2025-08-12",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202508/12/93729.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "循轨识弊 速破困局—科义轨道式巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/202508/12/93729.html",
    "is_real": true
  },
  {
    "id": 118,
    "lead_type": "procurement",
    "title": "科义履带式巡检机器人：中国 AI 场景落地的工业实践范本",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "科义履带式巡检机器人：中国 AI 场景落地的工业实践范本",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-07-18",
    "published_at": "2025-06-27",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202506/27/93312.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "科义履带式巡检机器人：中国 AI 场景落地的工业实践范本\n来源:中国机器人网 https://www.robot-china.com/news/202506/27/93312.html",
    "is_real": true
  },
  {
    "id": 119,
    "lead_type": "procurement",
    "title": "科义机器人迎领导参观 以创新技术与前瞻建议驱动发展",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "科义机器人迎领导参观 以创新技术与前瞻建议驱动发展",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-07-07",
    "published_at": "2025-06-16",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202506/16/93173.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "科义机器人迎领导参观 以创新技术与前瞻建议驱动发展\n来源:中国机器人网 https://www.robot-china.com/news/202506/16/93173.html",
    "is_real": true
  },
  {
    "id": 120,
    "lead_type": "procurement",
    "title": "正崴旗下星科推AI机器人平台！瞄准200亿美元安防巡检商机",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "正崴旗下星科推AI机器人平台！瞄准200亿美元安防巡检商机",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-06-27",
    "published_at": "2025-06-06",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202506/06/93045.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "正崴旗下星科推AI机器人平台！瞄准200亿美元安防巡检商机\n来源:中国机器人网 https://www.robot-china.com/news/202506/06/93045.html",
    "is_real": true
  },
  {
    "id": 121,
    "lead_type": "procurement",
    "title": "2025中国智能巡检厂商TOP榜发布：优艾智合领衔，七腾等企业强势上榜",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "2025中国智能巡检厂商TOP榜发布：优艾智合领衔，七腾等企业强势上榜",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-05-14",
    "published_at": "2025-04-23",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202504/23/92641.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "2025中国智能巡检厂商TOP榜发布：优艾智合领衔，七腾等企业强势上榜\n来源:中国机器人网 https://www.robot-china.com/news/202504/23/92641.html",
    "is_real": true
  },
  {
    "id": 122,
    "lead_type": "procurement",
    "title": "灵眸智巡 —基于深度学习的消防巡检机器人系统构建",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "灵眸智巡 —基于深度学习的消防巡检机器人系统构建",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-04-21",
    "published_at": "2025-03-31",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202503/31/92353.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "灵眸智巡 —基于深度学习的消防巡检机器人系统构建\n来源:中国机器人网 https://www.robot-china.com/news/202503/31/92353.html",
    "is_real": true
  },
  {
    "id": 123,
    "lead_type": "procurement",
    "title": "机器狗和无人车“丝滑”搭档 杭州电力上线一体巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器狗和无人车“丝滑”搭档 杭州电力上线一体巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-04-11",
    "published_at": "2025-03-21",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202503/21/92209.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器狗和无人车“丝滑”搭档 杭州电力上线一体巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/202503/21/92209.html",
    "is_real": true
  },
  {
    "id": 124,
    "lead_type": "procurement",
    "title": "优艾智合巡检机器人领跑行业，多领域应用助力智能化升级",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "优艾智合巡检机器人领跑行业，多领域应用助力智能化升级",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-04-02",
    "published_at": "2025-03-12",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202503/12/92059.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "优艾智合巡检机器人领跑行业，多领域应用助力智能化升级\n来源:中国机器人网 https://www.robot-china.com/news/202503/12/92059.html",
    "is_real": true
  },
  {
    "id": 125,
    "lead_type": "procurement",
    "title": "浙江义乌率先引入大疆机场 3 无人值守无人机平台，用于低空公路水务智能巡检",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "浙江义乌率先引入大疆机场 3 无人值守无人机平台，用于低空公路水务智能巡检",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["浙江"],
    "deadline": "2025-03-31",
    "published_at": "2025-03-10",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202503/10/92031.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "浙江义乌率先引入大疆机场 3 无人值守无人机平台，用于低空公路水务智能巡检\n来源:中国机器人网 https://www.robot-china.com/news/202503/10/92031.html",
    "is_real": true
  },
  {
    "id": 126,
    "lead_type": "procurement",
    "title": "创新不止步！七腾三款防爆轮式机器人，开启智能巡检新时代",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "创新不止步！七腾三款防爆轮式机器人，开启智能巡检新时代",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-18",
    "published_at": "2025-02-25",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/25/91867.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "创新不止步！七腾三款防爆轮式机器人，开启智能巡检新时代\n来源:中国机器人网 https://www.robot-china.com/news/202502/25/91867.html",
    "is_real": true
  },
  {
    "id": 127,
    "lead_type": "procurement",
    "title": "不止防爆四足，七腾机器人全新轮式产品解锁全新巡检场景解决方案",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "不止防爆四足，七腾机器人全新轮式产品解锁全新巡检场景解决方案",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-18",
    "published_at": "2025-02-25",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/25/91866.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "不止防爆四足，七腾机器人全新轮式产品解锁全新巡检场景解决方案\n来源:中国机器人网 https://www.robot-china.com/news/202502/25/91866.html",
    "is_real": true
  },
  {
    "id": 128,
    "lead_type": "procurement",
    "title": "解决传统轮式巡检痛点，七腾机器人新品带来巡检新方案",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "解决传统轮式巡检痛点，七腾机器人新品带来巡检新方案",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-18",
    "published_at": "2025-02-25",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/25/91865.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "解决传统轮式巡检痛点，七腾机器人新品带来巡检新方案\n来源:中国机器人网 https://www.robot-china.com/news/202502/25/91865.html",
    "is_real": true
  },
  {
    "id": 129,
    "lead_type": "procurement",
    "title": "七腾机器人轮式新品亮相：用高防爆和小型化重塑石油化工巡检格局",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "七腾机器人轮式新品亮相：用高防爆和小型化重塑石油化工巡检格局",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-18",
    "published_at": "2025-02-25",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/25/91864.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "七腾机器人轮式新品亮相：用高防爆和小型化重塑石油化工巡检格局\n来源:中国机器人网 https://www.robot-china.com/news/202502/25/91864.html",
    "is_real": true
  },
  {
    "id": 130,
    "lead_type": "procurement",
    "title": "科远智慧：公司的机器人业务主要应用于能源电力行业的清洗、钢铁冶金的无人行车以及巡检等方面",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "科远智慧：公司的机器人业务主要应用于能源电力行业的清洗、钢铁冶金的无人行车以及巡检等方面",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-05",
    "published_at": "2025-02-12",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/12/91646.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "科远智慧：公司的机器人业务主要应用于能源电力行业的清洗、钢铁冶金的无人行车以及巡检等方面\n来源:中国机器人网 https://www.robot-china.com/news/202502/12/91646.html",
    "is_real": true
  },
  {
    "id": 131,
    "lead_type": "procurement",
    "title": "申昊科技：“一种自平衡巡检机器人”取得专利证书",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "申昊科技：“一种自平衡巡检机器人”取得专利证书",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-03-01",
    "published_at": "2025-02-08",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/08/91552.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "申昊科技：“一种自平衡巡检机器人”取得专利证书\n来源:中国机器人网 https://www.robot-china.com/news/202502/08/91552.html",
    "is_real": true
  },
  {
    "id": 132,
    "lead_type": "procurement",
    "title": "格灵深瞳：机器人感知与控制技术是公司的核心技术之一，目前主要应用于工业巡检领域",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "格灵深瞳：机器人感知与控制技术是公司的核心技术之一，目前主要应用于工业巡检领域",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-02-28",
    "published_at": "2025-02-07",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202502/07/91507.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "格灵深瞳：机器人感知与控制技术是公司的核心技术之一，目前主要应用于工业巡检领域\n来源:中国机器人网 https://www.robot-china.com/news/202502/07/91507.html",
    "is_real": true
  },
  {
    "id": 133,
    "lead_type": "procurement",
    "title": "政启新程、市撑大势、技筑远景，智能巡检解锁无限可能",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "政启新程、市撑大势、技筑远景，智能巡检解锁无限可能",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2025-01-30",
    "published_at": "2025-01-09",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202501/09/91272.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "政启新程、市撑大势、技筑远景，智能巡检解锁无限可能\n来源:中国机器人网 https://www.robot-china.com/news/202501/09/91272.html",
    "is_real": true
  },
  {
    "id": 134,
    "lead_type": "procurement",
    "title": "合肥8号线迎开通前“大考” 智能巡检机器人“上岗”",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "合肥8号线迎开通前“大考” 智能巡检机器人“上岗”",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2024-12-24",
    "published_at": "2024-12-03",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/202412/03/90695.html"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "合肥8号线迎开通前“大考” 智能巡检机器人“上岗”\n来源:中国机器人网 https://www.robot-china.com/news/202412/03/90695.html",
    "is_real": true
  },
  {
    "id": 135,
    "lead_type": "procurement",
    "title": "巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 136,
    "lead_type": "procurement",
    "title": "智能巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 137,
    "lead_type": "procurement",
    "title": "机器人巡检",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "机器人巡检",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%B7%A1%E6%A3%80"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "机器人巡检\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%B7%A1%E6%A3%80",
    "is_real": true
  },
  {
    "id": 138,
    "lead_type": "procurement",
    "title": "变电站智能巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "变电站智能巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%8F%98%E7%94%B5%E7%AB%99%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "变电站智能巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%8F%98%E7%94%B5%E7%AB%99%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 139,
    "lead_type": "procurement",
    "title": "输电线路巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "输电线路巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E8%BE%93%E7%94%B5%E7%BA%BF%E8%B7%AF%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "输电线路巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E8%BE%93%E7%94%B5%E7%BA%BF%E8%B7%AF%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 140,
    "lead_type": "procurement",
    "title": "电力巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "电力巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E7%94%B5%E5%8A%9B%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "电力巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E7%94%B5%E5%8A%9B%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 141,
    "lead_type": "procurement",
    "title": "变电站巡检机器人",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "变电站巡检机器人",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E5%8F%98%E7%94%B5%E7%AB%99%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "变电站巡检机器人\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E5%8F%98%E7%94%B5%E7%AB%99%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8%E4%BA%BA",
    "is_real": true
  },
  {
    "id": 142,
    "lead_type": "procurement",
    "title": "电力智能巡检机器",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "电力智能巡检机器",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国机器人网",
    "sources": [{"source_name": "中国机器人网", "url": "https://www.robot-china.com/news/search.php?kw=%E7%94%B5%E5%8A%9B%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "电力智能巡检机器\n来源:中国机器人网 https://www.robot-china.com/news/search.php?kw=%E7%94%B5%E5%8A%9B%E6%99%BA%E8%83%BD%E5%B7%A1%E6%A3%80%E6%9C%BA%E5%99%A8",
    "is_real": true
  },
  {
    "id": 146,
    "lead_type": "procurement",
    "title": "上半年机械工业规上企业增加值同比增长9% 经济效益回稳向好",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "上半年机械工业规上企业增加值同比增长9% 经济效益回稳向好",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["全国"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国公共采购网",
    "sources": [{"source_name": "中国公共采购网", "url": "http://www.cgpnews.cn/articles/72390"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "上半年机械工业规上企业增加值同比增长9% 经济效益回稳向好\n来源:中国公共采购网 http://www.cgpnews.cn/articles/72390",
    "is_real": true
  },
  {
    "id": 147,
    "lead_type": "procurement",
    "title": "智能体服务进入宁夏政府“购物车”",
    "product_category": "other",
    "product_category_raw": "示例类别",
    "components": ["待补充"],
    "demand_side_raw": "见公告原文",
    "demand_side_size": "medium",
    "scale_raw": "智能体服务进入宁夏政府“购物车”",
    "est_qty_min": null,
    "est_qty_max": null,
    "qty_unit": "",
    "qty_period": "",
    "regions": ["宁夏"],
    "deadline": "2026-08-05",
    "published_at": "2026-07-15",
    "confidence": 0.7,
    "extract_notes": "自动抓取自 中国公共采购网",
    "sources": [{"source_name": "中国公共采购网", "url": "http://www.cgpnews.cn/articles/75321"}],
    "status": "new",
    "status_note": "",
    "merged_count": 1,
    "raw_content": "智能体服务进入宁夏政府“购物车”\n来源:中国公共采购网 http://www.cgpnews.cn/articles/75321",
    "is_real": true
  }
];

// 元数据:枚举映射
window.META = {
  lead_type: {
    procurement: { label: "采购", chipClass: "chip-blue" },
    custom:      { label: "定制", chipClass: "chip-violet" },
    solution:    { label: "方案", chipClass: "chip-amber" },
    oem:         { label: "代工", chipClass: "chip-cyan" },
    other:       { label: "其他", chipClass: "chip-slate" }
  },
  product_category: {
    lawn_mower:  { label: "割草机器人", color: "#16a34a" },
    cleaning:    { label: "清洁机器人", color: "#0ea5e9" },
    inspection:  { label: "巡检机器人", color: "#f59e0b" },
    delivery:    { label: "配送机器人", color: "#ef4444" },
    agv_amr:     { label: "AGV/AMR", color: "#8b5cf6" },
    robotic_arm: { label: "机械臂", color: "#ec4899" },
    humanoid:    { label: "人形机器人", color: "#06b6d4" },
    service:     { label: "服务机器人", color: "#84cc16" },
    special:     { label: "特种机器人", color: "#f97316" },
    component:   { label: "零部件", color: "#64748b" },
    other:       { label: "其他", color: "#94a3b8" }
  },
  demand_side_size: {
    large:   "大型",
    medium:  "中型",
    small:   "小型",
    unknown: "未知"
  },
  status: {
    new:       { label: "待跟进", chipClass: "chip-blue" },
    contacted: { label: "已联系", chipClass: "chip-amber" },
    quoted:    { label: "已报价", chipClass: "chip-violet" },
    won:       { label: "已中标", chipClass: "chip-green" },
    lost:      { label: "未中标", chipClass: "chip-rose" },
    ignored:   { label: "不跟进", chipClass: "chip-slate" }
  }
};
